default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('APP_DATABASE_HOST') { 'db' } %>
  username: <%= ENV.fetch('APP_DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('APP_DATABASE_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: rails_first_osk_development

test:
  <<: *default
  host: <%= ENV.fetch('APP_DATABASE_HOST') { 'db' } %>
  database: rails_first_osk_test

production:
  <<: *default
  database: rails_first_osk_production
  url: <%= ENV['DATABASE_URL'] %>

